-- This is an example SQLX file to help you learn the basics of Dataform.
-- Visit https://cloud.google.com/dataform/docs/sql-workflows for more information on how to configure your SQL workflow.

-- You can delete this file, then commit and push your changes to your repository when you are ready.

-- Config blocks allow you to configure, document, and test your data assets.
config {
  type: "view", // Creates a view in BigQuery. Try changing to "table" instead.
  columns: {
    test: "A description for the test column", // Column descriptions are pushed to BigQuery.
  }
}

-- The rest of a SQLX file contains your SELECT statement used to create the table.

SELECT 
primary_type,
  COUNT(*) AS crime_count
FROM
  bigquery-public-data.austin_crime.crime
WHERE 
  primary_type IS NOT NULL
GROUP BY
 primary_type
ORDER  BY
  crime_count DESC
LIMIT  5 
